# Generated by Django 4.1.3 on 2022-11-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='fgg', upload_to='images'),
            preserve_default=False,
        ),
    ]
